[build]
  publish = "dist/frontend"
  command = "npm install --legacy-peer-deps && npm run build:prod"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200